# Generated by Django 5.0.4 on 2024-07-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products_prices_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categoryId',
            field=models.IntegerField(default=0),
        ),
    ]
