# Generated by Django 5.0.4 on 2024-07-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_products_categoryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='productsId',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='prices',
            old_name='productsId',
            new_name='product',
        ),
    ]
