# Generated by Django 5.0.4 on 2024-07-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_images_product_remove_prices_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='productt',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='prices',
            old_name='productt',
            new_name='product',
        ),
    ]
